### ISSUE TITLE
Doesn't work with netcoreapp3.1

### ISSUE THREAD

**Issue by tomeinar** [jkmu/Saml2.Authentication.Core#13]
We tried using your package from a core 3.1 project, but it fails during start up. I've upgraded both your projects, but haven't been able to test it properly, apart from verifying that we can start the webapp and that the package doesn't fail during startup anymore.

**Comment by heebtob** [comment]
Did you succeed with .Net Core 3.1? 
I'm using .Net 5 in my project and it has to support SAML 2.0.
Could you share some of your findings?

**Comment by tomeinar** [comment]
Well, I did something and made a pull request, it seems. I can't really remember, we abandoned SAML for a period of time. We're picking it up again though. I've notived that there is another library mentioned here: https://developer.okta.com/blog/2020/10/23/how-to-authenticate-with-saml-in-aspnet-core-and-csharp

Might be worth checking out.

**Comment by jkmu** [comment]
Doesnt support  .Net Core 3.1 yet, never got time to look at the PR but hopefully this weekend

**Comment by jkmu** [comment]
@heebtob New version supports netcoreapp3.1 now. Thanks @tomeinar for the PR
