### ISSUE TITLE
Is it possible to use this with JWT tokens?

### ISSUE THREAD

**Issue by mkgn** [jkmu/Saml2.Authentication.Core#15]
My app uses JWT authentication. How should be the flow if I use this with JWT? Like;

Once a SAML end point gets data (I am using IdP initiated, so I expect the SAML responce from IdP), I should create a token and forward it to my client (Angular app?)

**Comment by memadk** [comment]
Did you manage to get such a flow to work?
I have the same issue.

**Comment by jkmu** [comment]
I have not tested such a flow. Theoretically what you are saying should work.

**Comment by memadk** [comment]
Is there a way to initiate the Saml login flow (Redirect to IDP) without using MVC and the Challenge request. 
I would like to make a call from angular to for instance and api-controller, that would make a redirect to the IDP.

**Comment by memadk** [comment]
So the way I made this work, was by adding a cookie protected api action, the returned a JWT token. This token could the be used as authorization for rest of my api.
