### ISSUE TITLE
How to make this work behind loadbalancer

### ISSUE THREAD

**Issue by memadk** [jkmu/Saml2.Authentication.Core#16]
I am using (a fork) of this library, but I don't know how to makes it work behind a load-balancer. Is it possible to make it work or do I need to somehow always return to the same server behind the load-balancer?

**Comment by jkmu** [comment]
This is no different than any other normal web application. The same way you would do load balancing in a web application should work for this too. 

If you are using a server farm remember to configure DataProtection. 

Good luck do not hesitate to ask here if you get into problems.
