### ISSUE TITLE
HTTP Redirect Binding uses HTTP 301 instead of HTTP 302

### ISSUE THREAD

**Issue by andysleigh** [jkmu/Saml2.Authentication.Core#5]
When performing an SP initiated sign on, the redirect that is given (in SamlService.cs) uses HTTP code 301, which is a permanent redirect. Most browsers cache these responses for a very long time, and so the next time the browser accesses the server, they reuse the old redirect with a possibly-expired AuthRequest. The SAML spec requires that either a 303 or 302 redirect should be used (see [https://docs.oasis-open.org/security/saml/v2.0/saml-bindings-2.0-os.pdf](https://docs.oasis-open.org/security/saml/v2.0/saml-bindings-2.0-os.pdf) page 19)

>  the HTTP status MUST be either 303 or 302.

On a related point, the spec also recommend the use of cache headers to prevent caching as quoted below.

> When returning SAML protocol messages using HTTP 1.1, HTTP responders SHOULD:
• Include a Cache-Control header field set to "no-cache, no-store".
• Include a Pragma header field set to "no-cache".

**Comment by jkmu** [comment]
Took a look at this. Its now fixed in v1.2.1
- Thanks!
