### ISSUE TITLE
Question: act as saml2 identity provider?

### ISSUE THREAD

**Issue by svrooij** [jkmu/Saml2.Authentication.Core#9]
Will I be able to use this library as a saml2 identity provider?
I would like to create a custom bridge between OpenID Connect and saml2. So the user wants to login to some service that supports saml2 for SSO. They will be redirected to my dotnet core application. That logs the user in (if not already logged-in) through OpenID Connect, and then the user is redirected back to the external service where it’s logged-in with the saml2 protocol

**Comment by jkmu** [comment]
No this library is only for the Service provider

**Comment by svrooij** [comment]
Thanks for the answerr
